BACKGROUND_MUSIC = "sounds/background/background.ogg"
BULLET_SFX = "sounds/lazer.wav" 
EXPLOSION_SFX = "sounds/11_EXPRETAP.wav"
TURRET_BULLET_SFX = "sounds/03_TEMP10.wav"
START_MUSIC = "sounds/start music.ogg"
END_MUSIC = "sounds/end music.ogg"
SCREEN_WIDTH = 624
SCREEN_HEIGHT = 480
SCROLL_RATE = 1
COLS = 26
ROWS = 180
PORT = 4141
PROTOCOL = 2 # For Pickle. 0 is plain text.
